### ISSUE TITLE
is it error?

### ISSUE THREAD

**Issue by zhangnn520** [atiumcache/pure-recipe#18]
recipe-scrapers exception: Website (ncbi.nlm.nih.gov) not supported.

**Comment by zhangnn520** [comment]
python pure_recipe.py save https://www.ncbi.nlm.nih.gov/pubmed/36371025

Could not scrape recipe, error: recipe-scrapers exception: Website (ncbi.nlm.nih.gov) not supported.

An error occurred: local variable 'scraper' referenced before assignment

**Comment by atiumcache** [comment]
That's not a recipe, that's an academic publication.
