### ISSUE TITLE
Missing virtual environment information in .gitignore

### ISSUE THREAD

**Issue by rileyyy** [atiumcache/pure-recipe#2]
I'll add this as an issue so that you can choose how you would like to resolve it.
When working in python, I prefer to use a virtual environment to keep dependencies clean from other projects.
In this case, when I went to commit a bugfix for a branch I noticed that git was attempting to commit my `venv/` directory.

Possible solutions:

1. **Ignore me.** A perfectly fine solution, people should commit only what they intend to change, and I am lazy so I typically use `git add .`.
2. **Add the following section to your `.gitignore`**  This should ignore any virtual environment directories that are created by the various environments:
```
# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/
```

3. **Use an existing python-oriented .gitignore** (and add your specific files to the end).  [This](https://github.com/rileyyy/python-driver/blob/main/.gitignore) is the one I use for work and it covers pretty much everything that we create.  Some of it may be a bit superfluous if you're not using Sphinx for documentation or SageMath for example.  But those sections can be removed at your discression.

**Comment by atiumcache** [comment]
Thanks! Just updated.
