### ISSUE TITLE
Incorrect examples?

### ISSUE THREAD

**Issue by rileyyy** [atiumcache/pure-recipe#6]
### Issue encountered
When I attempt to use the examples provided:
`python pure_recipe.py view https://www.seriouseats.com/potato-wedges-recipe-5217319`
I receive the following error:
```
λ python pure_recipe.py view https://www.seriouseats.com/potato-wedges-recipe-5217319
usage: Pure Recipe [-h] [--url URL] {view,save,list,browse}
Pure Recipe: error: unrecognized arguments: https://www.seriouseats.com/potato-wedges-recipe-5217319
```

### Expected outcome
Using the provided examples, a valid output should be displayed.

### Present workaround
The expected outcome can be achieved by running the following command (adds `--url` before the url):
`python pure_recipe.py view --url https://www.seriouseats.com/potato-wedges-recipe-5217319`
This displays the expected output (the ingredients and directions neatly formatted) but also ends with `Error in view_in_terminal function.`

![image](https://github.com/atiumcache/pure-recipe/assets/9386096/146821a4-1b3a-4944-9353-a94a2ab351e9)

**Comment by atiumcache** [comment]
Fixed the way in which arguments are parsed, so that all 4 functions (view, save, list, browse) work as described in the README.
