### ISSUE TITLE
Save does not correctly create the filename

### ISSUE THREAD

**Issue by rileyyy** [atiumcache/pure-recipe#7]
### Issue encountered
Attempting to save a recipe using the example recipe created the filename with the word recipes at the front:
![image](https://github.com/atiumcache/pure-recipe/assets/9386096/b6372e5a-5e9e-48b2-ab1f-0747f8091708)

### Expected result
The file should be named `crispy-baked-potato-wedges.md` and located inside the `recipes/` directory.

You could consider the .replace() function that is built into python as well for name sanitization.
e.g. `title = scraper.title().replace(' ', '-') + ".md"`

**Comment by atiumcache** [comment]
Thanks a bunch @rileyyy for the thorough testing and suggestions. Much appreciated.

**Comment by rileyyy** [comment]
Not a problem!  I'll pull down the latest changes later when I have some time and give it another go. Seems like a super handy utility!
